### ISSUE TITLE
Clean up textdraws correctly

### ISSUE THREAD

**Issue by Pottus** [Southclaws/progress2#11]
No clean up code for OnFilterScriptExit() / OnGameModeExit() I had to add this myself.

**Comment by Southclaws** [comment]
Ah yeah I never used filterscripts or gamemodes in such a way that was affected by this so I forgot! A PR would be handy if you implemented it directly into the source.

**Comment by Pottus** [comment]
Let me see here.....

**Comment by AmirSavand** [comment]
@Southclaws but isn't this cleaning up at https://github.com/Southclaws/progress2/blob/master/progress2.inc#L441 ?

**Comment by Southclaws** [comment]
Yes, you replied to an issue from 2016, I just forgot to close it!

**Comment by AmirSavand** [comment]
Glad I did.
