### ISSUE TITLE
Issue with hidden playerbars

### ISSUE THREAD

**Issue by MichaelBelgium** [Southclaws/progress2#18]
For some reason, when the progressbar is hidden, this if statement returns false when it should be true. And my common sense says this should work also when playerbars are hidden (cuz I have a toggle command to display or hide the progressbar)

`if(GetPlayerProgressBarValue(playerid,Player_Token[playerid][b_Level]) >= GetPlayerProgressBarMaxValue(playerid,Player_Token[playerid][b_Level]))`

EDIT; ok - this issue is in 2.0.3, I updated to the latest in case already
EDIT2: ok, no it might be because of SetPlayerProgressBarValue that displays the progressbar when it's hidden
EDIT3: well i can fix it in my code by doing this before the if statement
`SetPlayerProgressBarValue(playerid,Player_Token[playerid][b_Level],Player_Token[playerid][b_LevelVal]);
		if(!Player[playerid][Toggle][4]) 
			HidePlayerProgressBar(playerid, Player_Token[playerid][b_Level]);`

Instead of
`if(Player[playerid][Toggle][4]) SetPlayerProgressBarValue(playerid,Player_Token[playerid][b_Level],Player_Token[playerid][b_LevelVal]);`

So after all idk the point of this issue, Or maybe you can add `bool:pbar_hidden` in E_BAR_DATA and work from there on - If you're bored you can do it or so :p Your choice if u want to do it

**Comment by Southclaws** [comment]
2.1.3 should work fine looking at the code, but I should add an hidden check to https://github.com/Southclaw/progress2/blob/master/progress2.inc#L661

**Comment by MichaelBelgium** [comment]
Okay, great

EDIT: yeah it's just adding `if(pbar_Data[playerid][barid][pbar_show])` in front
