### ISSUE TITLE
is this cross platform UI ?

### ISSUE THREAD

**Issue by nvcken** [Southclaws/progress2#23]

**Comment by Southclaws** [comment]
I'm not sure what you mean by this, can you elaborate?

**Comment by nvcken** [comment]
Sorry, is this process UI bar can run on any platforms likes mobile & web ?

**Comment by ADRFranklin** [comment]
> Sorry, is this process UI bar can run on any platforms likes mobile & web ?

Hi, this is a UI element for a third party mod that implements a progress bar. 

This can not be used in the way I think you want it to be used. Like a real world application.

**Comment by nvcken** [comment]
just only for SA game mod , is it right ?

**Comment by Southclaws** [comment]
Yes, this is only for SA:MP.
