### ISSUE TITLE
Found a small mistake: This causes the fill color of the progress bar to be black all the time

### ISSUE THREAD

**Issue by ghost** [Southclaws/progress2#50]
Found a small mistake: This causes the fill color of the progress bar to be black all the time

line:485 Wrong
`pbar_TextDraw[playerid][barid][pbar_main] = ptd_fill;`

line:485 It should be changed to
`pbar_TextDraw[playerid][barid][pbar_fill] = ptd_fill;`

**Comment by MuthaX** [comment]
The mistake was at 487 line. You can create pull request with fix.
I'm created it (#51) already and mentioned you.
